[project]
name = "agentspace-lab1"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "google-adk==1.16.0",
    "google-auth-oauthlib>=1.2.2",
    "google-cloud-aiplatform==1.121.0",
    "google-genai==1.45.0",
    "ipykernel>=6.30.0",
]
